version: "3.8"
services:
  app_server:
    build: .
    restart: always
    ports:
      - 8080:8090
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: productsDB
      MYSQL_USER: techsingou
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234



